### ISSUE TITLE
crash if file does not have a trailing newline

### ISSUE THREAD

**Issue by jimhester** [jimhester/vroom#40]

**Comment by jimhester** [comment]
Fixed by 5f9c3b4bc33dfaf25c682ce296512f1a44140852

**Comment by henry090** [comment]
This problem still exists, even in development version. @jimhester 

```
Files must end with a newline
```

**Comment by jimhester** [comment]
That is an error message, not a crash, for vroom to read them files must end in a newline.

**Comment by mgirlich** [comment]
what do about automatically (controlled via a parameter) adding a newline to the end of a file if it doesn't have one? Otherwise, I imagine many people using this workaround in their own code (I have a csv file from Excel that doesn't end in a newline so that might be quite a common problem...).

**Comment by jimhester** [comment]
vroom now has a workaround using a file connection to allow users to read files with no trailing newline.
